/*
 * ultrasonic.h
 *
 *  Created on: Feb 28, 2022
 *      Author: MahmoudLabib
 */

#ifndef SRC_EHAL_ULTRASONIC_ULTRASONIC_H_
#define SRC_EHAL_ULTRASONIC_ULTRASONIC_H_

#include "../../Utils/std_types.h"
#include "../../MCAL/ICU/icu.h"
#include "../../MCAL/GPIO/gpio.h"
/*
 * Description:
      ➢ Initialize the ICU driver as required.
      ➢ Setup the ICU call back function.
      ➢ Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);


/*
 * Description
      ➢ Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);


/*
 * Description
      ➢ Send the trigger pulse by using Ultrasonic_Trigger function.
      ➢ Start the measurements by the ICU from this moment.
      • Inputs: None
      • Return: The measured distance in Centimeter.
 *
 */
uint16 Ultrasonic_readDistance(void);


/*
 *Description
     ➢ This is the call back function called by the ICU driver.
     ➢ This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);



#endif /* SRC_EHAL_ULTRASONIC_ULTRASONIC_H_ */
